### ISSUE TITLE
练习JS+回复算法: 74. Search a 2D Matrix 用Javascript解一遍

### ISSUE THREAD

**Issue by pomo651** [pomo651/algo#8]
https://leetcode.com/problems/search-a-2d-matrix/ 
用JS 写一遍

**Comment by cathy651** [comment]
done

**Comment by pomo651** [comment]
> done

请注意看给你assign的任务: @cathy651 
1.要求只说了LC 240 用JS写一遍，没说LC 240需要你再Java写一遍，Java 我已经写过一遍了，你既然review了我的Code 而且Code是你merge的，就证明Java你是会写的。
2.没要求写LC1293
